version = "3.11.5"
runner.dialect = scala3
align.preset = more
maxColumn = 150
newlines.source = fold
newlines.forceBeforeMultilineAssign = any

rewrite.rules = [Imports, SortModifiers]
rewrite.imports.sort = scalastyle
rewrite.imports.groups = [
    ["java\\..*"],
    ["scala\\..*"]
]
rewrite.sortModifiers.preset = styleGuide

rewrite.scala3.convertToNewSyntax = true
rewrite.scala3.removeOptionalBraces = true

fileOverride {
    "glob:**/*.sbt" {
        newlines.source = keep
        newlines.forceBeforeMultilineAssign = never
    }
    "glob:**/project/*.scala" {
        runner.dialect = scala212
        rewrite.scala3.convertToNewSyntax = false
    }
}
