version = "3.11.1"
runner.dialect = scala3
align.preset = more
maxColumn = 150

rewrite.rules = [Imports, SortModifiers]
rewrite.imports.sort = scalastyle
rewrite.imports.groups = [
    ["java\\..*"],
    ["scala\\..*"]
]
rewrite.sortModifiers.preset = styleGuide

rewrite.scala3.convertToNewSyntax = true

fileOverride {
    "glob:**/project/*.scala" {
        runner.dialect = scala212
        rewrite.scala3.convertToNewSyntax = false
    }
}
